### PR TITLE
(RE-12082) libuser fixups

### PR DESCRIPTION
**Pull request by mwaggett**
see individual commit messages for details

### CODE REVIEW

**Comment by mwaggett** [comment]
I can build and install on el 7 and ubuntu 18.04, but there's a bug for debian 8 and ubuntu 16.04 that we'll need to work around.

**Comment by mwaggett** [comment]
alrighty, built everything again successfully and confirmed that I can now install and start the service on ubuntu-16.04-x86_64 (xenial) and el-6-x86_64, but turns out there's no libuser package for sles.

**Comment by sarameisburger** [comment]
@mwaggett can this be closed until work resumes on it?

**Comment by mwaggett** [comment]
@sarameisburger I just want to make sure this work doesn't get lost when we re-do the work for https://tickets.puppetlabs.com/browse/PE-24606.

**Comment by sarameisburger** [comment]
@mwaggett the work will still be on your fork

**Comment by mwaggett** [comment]
yeah, but I feel like no one besides me would know to look there and I won't necessarily be the one doing the work.
¯\_(ツ)_/¯  if you feel strongly about closing this, you can.

**Comment by sarameisburger** [comment]
@mwaggett we can add a link to the work in the ticket so whomever picks up the ticket knows where to look

**Pull request closed without merging**
