### PR TITLE
remove cprice404

### PR DESCRIPTION
**Pull request by call**

### CODE REVIEW

**Comment by stahnma** [comment]
This is an open source project, if @cprice404 wants to stay on, seems like he can.

**Comment by underscorgan** [comment]
see also, #391

**Comment by call** [comment]
My understanding was that only Puppet employees belong in MAINTAINERS files. cc @theshanx @rick @stahnma

**Comment by underscorgan** [comment]
I'm going to close this since it's a dupe of #391 and there are duplicate conversations now.

**Pull request closed without merging**
