### PR TITLE
(maint) Remove cprice404 as maintainer

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by stahnma** [comment]
@cprice404 do you still want to be a maintainer on this very active open source project?

**Comment by cprice404** [comment]
@stahnma  o/

well, seeing as how I can't actually run it anymore, it probably doesn't make a ton of sense for me to be a maintainer :(

**Comment by steveax** [comment]
image

**Comment by call** [comment]
My understanding was that only Puppet employees belong in MAINTAINERS files. cc @theshanx @rick @stahnma

**Pull request merged**
