### PR TITLE
(maint) Update changelog for ezbake release

### PR DESCRIPTION
**Pull request by McdonaldSeanp**

### CODE REVIEW

**Comment by mckern** [comment]
Ditch the RE ticket number in the PR and commit message, and I'll merge it.

**Comment by shrug** [comment]
Can you add a summary of https://github.com/puppetlabs/ezbake/pull/295 to the changelog?

**Comment by mckern** [comment]
Oooh, that too! ^^^

**Comment by mckern** [comment]
@shrug do you mean #296? Sean didn't work 295 and we're not sure how to summarize that one succinctly.

**Comment by shrug** [comment]
No, I mean #295 - the changelog needs to summarize all of the changes since the last release. That one could be summarized as something like:

"Improved handling of mirrors and/or local repos for dependency resolution"

**Comment by McdonaldSeanp** [comment]
Alrighty, So since I don't know how else to describe it I just put that in there verbatim

**Comment by shrug** [comment]
:+1:

**Pull request merged**
