### PR TITLE
(maint) Backport Snapshot-Version Changes & Full Dependency Names

### PR DESCRIPTION
**Pull request by aperiodic**
Backport the recently merged changes on master to list specific snapshot versions included in a package and to have the full dependency symbol (including the group) in the description.

### CODE REVIEW

**Comment by underscorgan** [comment]
Can you please also include https://github.com/puppetlabs/ezbake/pull/403 ?

**Comment by aperiodic** [comment]
@underscorgan oh, of course. Updated.

**Comment by aperiodic** [comment]
@underscorgan is this good to go now? Does it need more changes?

**Comment by shrug** [comment]
With EZBAKE_NODEPLOY set, the stage command doesn't deploy the artifact, howver the build command fails if there's not a deployed artifact - is that intentional? it makes testing changes locally more difficult.

**Comment by aperiodic** [comment]
@shrug yes. I think the extra step it adds to testing local changes is worth being sure that we're not making unreproducible builds. There are a few different ways to make it [easier to deploy the snapshot](https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md#authentication), including just deploying once upfront and then setting EZBAKE_NODEPLOY

**Comment by shrug** [comment]
So for example, at the moment I'm trying to run test puppet-server builds in order to test some ezbake changes. Do we expect those to be deployed? I'll need to configure credentials to be able to deploy artifacts if that's the case

**Comment by aperiodic** [comment]
@shrug if it's building snapshot versions, then yes. Like most of our clojure projects, puppetserver is [configured to source deployment credentials from the environment](https://github.com/puppetlabs/puppetserver/blob/master/project.clj#L6), and the correct environment variables are already set [in the packaging-clj-lein-ezbake Jenkins job](https://github.com/puppetlabs/ci-job-configs/blob/master/resources/scripts/packaging-clj-lein-ezbake.sh).

**Comment by camlow325** [comment]
Like @shrug, I would really like to have a way to disable the `get-full-snapshot-version` functionality occasionally for local testing - maybe through the use of an extra `EZBAKE_NO_RESOLVE_SNAPSHOTS` variable or something if we don't want to overload the use of the `EZBAKE_NODEPLOY` variable.  I frequently find myself running "ezbake stage" locally for one-off, iterative puppetserver work and would like to just validate that content is staged properly by ezbake without having to rely upon having deployed something to an external repository.  I can hack around this for now by setting up an internal local file repository and doing a local deploy of puppetserver to that so that the stage command is able to resolve the dependency.  That process has been pretty tedious so far for me, though, and so just having a "buyer beware" way to turn it off at the command line would be very helpful.

**Comment by aperiodic** [comment]
@shrug @camlow325 I've added a commit that lets you set the `EZBAKE_ALLOW_UNREPRODUCIBLE_BUILDS` environment variable to bypass the deployed snapshot check.

**Comment by camlow325** [comment]
@aperiodic Thanks for doing that.  I think that is a good compromise.

**Comment by shrug** [comment]
@aperiodic thanks, mind adding that to the README and we'll get this in?

**Comment by aperiodic** [comment]
@shrug done

**Comment by shrug** [comment]
@camlow325 Did you want to take another look, or are you ok to merge?

**Comment by camlow325** [comment]
@shrug Feel free to merge if y'all are ok with it.  I just wanted to weigh in on the one part about resolving snapshot versions, which I'm good with.

**Pull request merged**
