### PR TITLE
(EZ-132) Change the wired-in settings for Java OOM handling.

### PR DESCRIPTION
**Pull request by e-gris**
Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by e-gris** [comment]
@underscorgan / @shrug This change seems possibly naive but I think it's the only thing we need. Thoughts?

**Comment by underscorgan** [comment]
@e-gris I think the main thing I'd want to have verified is whether this works in both java8 and java11 or just java11.

**Comment by e-gris** [comment]
Agreed. By Oracle's docs, it *should*. Any suggestions on an easy way to test that?

**Comment by e-gris** [comment]
A quick test; 'Point3d' is just a random bit of java code.

``` bash
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

$ java -XX:+IntentionalBadFlag Point3d
Unrecognized VM option 'IntentionalBadFlag'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

$ java -XX:+CrashOnOutOfMemoryError Point3d
pt1 = (0.0, 0.0, 0.0)
pt2 = (1.0, 2.0, 3.0)
Distance from (1.0, 2.0, 3.0) to (0.0, 0.0, 0.0) is 3.7416573867739413
$
```

**Comment by e-gris** [comment]
Friday moratorium. Will merge on Monday.

**Pull request merged**
