### PR TITLE
(EZ-141) Install java 11 on EL >= 8

### PR DESCRIPTION
**Pull request by e-gris**
Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by e-gris** [comment]
Still needs testing.

**Comment by e-gris** [comment]
Looks like fpm might not like the '(foo or bar)' syntax for --depend. Investigating.

**Comment by underscorgan** [comment]
> Looks like fpm might not like the '(foo or bar)' syntax for --depend. Investigating.

aw dang

**Comment by e-gris** [comment]
Progress. My local test almost works:

```
fpm -s dir --depends '(java-11-openjdk-headless or java-1.8.0-openjdk-headless)' -t rpm -n exgpkg source
```

However, the resulting package always prefers to install 1.8 regardless of the order specified. I'll keep poking.

**Comment by underscorgan** [comment]
just to keep some discussion in gh for history, we were talking about this earlier and the package preferring 1.8 is weird, but ok, as long as if java-11 is installed it doesn't also try to install java-1.8

**Comment by e-gris** [comment]
@Magisus PR lacks approval, likely because of my slightly disappointing and nebulously-phrased results. 

If it's OK to have java8 favored but java11 allowed, for some reason I've yet to uncover, give this an approval and I'll make the ezbake release.

**Comment by e-gris** [comment]
@underscorgan We should merge or delete this. IIRC, you recently did some work with this.

**Pull request closed without merging**
