### PR TITLE
(RE-13571) Add support for ubuntu-20.04 (focal) for FOSS only

### PR DESCRIPTION
**Pull request by mwaggett**
Please add all notable changes to the "Unreleased" section of the CHANGELOG.

### CODE REVIEW

**Comment by mwaggett** [comment]
will update the changelog after Maggie's PR goes in, so I can rebase against it

**Comment by underscorgan** [comment]
@mwaggett have you been able to do a test build with focal to confirm there are no other needed changes in fpm.rb (most likely would be java package names in my experience)

**Comment by mwaggett** [comment]
@underscorgan yep, builds just finished: http://builds.delivery.puppetlabs.net/puppetserver/6.12.2.SNAPSHOT.2020.08.17T1408/artifacts/deb/focal/puppet6/

**Comment by Magisus** [comment]
@mwaggett did you smoke test that package too? e.g. install + agent run?

**Comment by mwaggett** [comment]
@Magisus I installed and started the puppetserver service.. Looks like there are additional steps to run the agent, I'll see if I can figure that out.

**Comment by underscorgan** [comment]
@mwaggett let me know when you get it smoke tested and I'll get this merged / ezbake released

**Comment by mwaggett** [comment]
okay, I was able to do an agent run successfully.

**Pull request merged**
