### PR TITLE
(EZ-68) fix typo `EZbake` to `EZBake`

### PR DESCRIPTION
**Pull request by janelu2**
This is a fixup PR, changes two typos in EZBake.

### CODE REVIEW

**Comment by janelu2** [comment]
@haus looking ok?

**Comment by haus** [comment]
@janelu2 did you check the reload script for the same typo?

**Comment by janelu2** [comment]
@haus yep, that was the only typo. Also needed to cast the timeout "300" to a float. This fix will be up sooooooooooooooooooooooooooooooooooooon

**Comment by janelu2** [comment]
@haus ok, should be good to go now. do you see anything else?

**Comment by haus** [comment]
nope. seems good.

**Pull request merged**
