### PR TITLE
(EZ-72) support split bootstrap configuration

### PR DESCRIPTION
**Pull request by jpinsonault**
This PR is the same as the previous one that was merged and reverted (https://github.com/puppetlabs/ezbake/pull/305). This reverts that revert and adds one new commit to fix backwards compatibility, so that's all that's probably all you need to look at if you've seen the previous PR

### CODE REVIEW

**Comment by jpinsonault** [comment]
Also to convince myself backwards compatibility is preserved, I added this as a dependency to puppeterver's master branch and successfully built/installed/started puppetserver.

**Comment by haus** [comment]
@jpinsonault do you have a link to the jenkins job?

**Comment by jpinsonault** [comment]
http://jenkins-release.delivery.puppetlabs.net/job/puppetserver-packaging-2016-05-09-12-37-37-2.4.0.master.SNAPSHOT.2016.05.09T1237

**Comment by haus** [comment]
```rpm -qp --configfiles el/7/PC1/x86_64/puppetserver-2.4.0.master-0.1SNAPSHOT.2016.05.09T1237.el7.noarch.rpm
/etc/logrotate.d/puppetserver
/etc/puppetlabs/puppetserver/bootstrap.cfg
/etc/puppetlabs/puppetserver/conf.d/auth.conf
/etc/puppetlabs/puppetserver/conf.d/global.conf
/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf
/etc/puppetlabs/puppetserver/conf.d/web-routes.conf
/etc/puppetlabs/puppetserver/conf.d/webserver.conf
/etc/puppetlabs/puppetserver/logback.xml
/etc/puppetlabs/puppetserver/request-logging.xml
/etc/sysconfig/puppetserver
```

cool. i'd want to make sure that the system-config was *not* listed in the configfiles when it is split out from the ca/vcs stuff.

**Comment by jpinsonault** [comment]
@haus what makes a file listed as a --configfile file? Just being under /etc? The rpm man page is a little terse

**Comment by haus** [comment]
@jpinsonault looks like we define it here https://github.com/puppetlabs/ezbake/blob/master/resources/puppetlabs/lein-ezbake/template/foss/ext/redhat/ezbake.spec.erb#L206-L208, which looks fine for this use case.

**Comment by jpinsonault** [comment]
@haus ahh, ok. Thanks

**Comment by cprice404** [comment]
LGTM, +1.  @melissa since we broke you last time I merged this, let me know if you have any interest in reviewing before I merge it again :)

**Pull request merged**
